-- Inicialización de Base de Datos para Sistema de Confort Térmico

-- 1. Tabla de Aulas (Espacios a monitorear)
create table public.aulas (
  id bigint generated by default as identity primary key,
  nombre text not null,
  descripcion text,
  codigo_qr_url text, -- URL o identificador para generar el QR
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 2. Tabla de Perfiles (Extensión de auth.users para recompensas)
create table public.perfiles (
  id uuid references auth.users not null primary key,
  email text,
  puntos int default 0,
  updated_at timestamp with time zone
);

-- Trigger para crear perfil automáticamente al registrarse
create or replace function public.handle_new_user() 
returns trigger as $$
begin
  insert into public.perfiles (id, email)
  values (new.id, new.email);
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- 3. Tabla de Feedback (Votos de confort)
create table public.feedback (
  id bigint generated by default as identity primary key,
  aula_id bigint references public.aulas not null,
  user_id uuid references auth.users, -- Nulo si es anónimo
  session_id text, -- Identificador para usuarios anónimos (generado en cliente)
  voto int not null check (voto >= -2 and voto <= 2), -- Escala: -2 (Muy frío) a 2 (Muy calor)
  comentario text,
  ip_address text, -- Para control de spam (opcional, cuidado con GDPR)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 4. Tabla de Mediciones (Datos de sensores hardware)
create table public.mediciones (
  id bigint generated by default as identity primary key,
  aula_id bigint references public.aulas not null,
  temperatura numeric(5,2),
  humedad numeric(5,2),
  co2 numeric(6,2),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- 5. Seguridad (Row Level Security - RLS)
alter table public.aulas enable row level security;
alter table public.perfiles enable row level security;
alter table public.feedback enable row level security;
alter table public.mediciones enable row level security;

-- Políticas Aulas
create policy "Aulas son públicas para lectura" 
  on public.aulas for select using (true);

-- Políticas Perfiles
create policy "Usuarios pueden ver sus propios puntos" 
  on public.perfiles for select using (auth.uid() = id);

-- Políticas Feedback
-- Cualquiera puede insertar (Anónimo o Autenticado)
create policy "Cualquiera puede enviar feedback" 
  on public.feedback for insert with check (true);

-- Solo admins o el propio usuario pueden ver (Simplificado: solo lectura pública de agregados se manejaría via vistas o funciones, aquí restringimos lectura directa)
create policy "Usuarios ven su propio feedback" 
  on public.feedback for select using (auth.uid() = user_id);

-- Políticas Mediciones
create policy "Mediciones son públicas para lectura" 
  on public.mediciones for select using (true);

-- 6. Funciones de Recompensa (Lógica básica)
-- Función para sumar puntos al votar (Solo autenticados)
create or replace function public.sumar_puntos_feedback()
returns trigger as $$
begin
  if new.user_id is not null then
    update public.perfiles
    set puntos = puntos + 10, -- 10 puntos por voto
        updated_at = now()
    where id = new.user_id;
  end if;
  return new;
end;
$$ language plpgsql security definer;

create trigger on_feedback_insert
  after insert on public.feedback
  for each row execute procedure public.sumar_puntos_feedback();

-- Datos Semilla (Ejemplo)
insert into public.aulas (nombre, descripcion) values 
('Aula 101', 'Laboratorio de Física'),
('Aula 202', 'Sala de Conferencias');
